package enums;

import java.util.List;

import static java.util.Arrays.asList;

public enum EquipmentEnum {
    NOTEBOOK(asList("notebook")),
    COMPUTADOR(asList("computador")),
    CELULAR(asList("celular")),
    TABLET(asList("tablet")),
    PC(asList("pc")),
    NOTEBOOK_GAMER(asList("notebook gamer")),
    COMPUTADOR_GAMER(asList("computador gamer")),
    MAQUINA(asList("maquina", "máquina")),
    PC_GAMER(asList("pc gamer")),
    GAMER(asList("gamer")),
    KINDLE(asList("kindle")),
    FONE(asList("fone")),
    MOUSE(asList("mouse")),
    TECLADO(asList("teclado")),
    MONITOR(asList("monitor")),
    SSD(asList("ssd")),
    HD(asList("hd")),
    DISCO_RIGIDO(asList("disco rigido", "disco rígido")),
    PLACA_VIDEO(asList("placa de video", "placa de vídeo")),
    VIDEO(asList("video", "vídeo")),
    MAE(asList("mae", "mãe")),
    SOM(asList("som")),
    REDE(asList("rede")),
    PLACA_MAE(asList("placa mae", "placa mãe", "placa-mãe")),
    PLACA_DE_SOM(asList("placa de som")),
    PLACA_DE_REDE(asList("placa de rede")),
    WEBCAM(asList("webcam")),
    CARREGADOR(asList("carregador")),
    OFFICE(asList("office")),
    ADOBE(asList("adobe")),
    NAVEGADOR(asList("navegador")),
    WINDOWS_XP(asList("windows xp", "win xp")),
    WINDOWS_VISTA(asList("windows vista", "win vista")),
    WINDOWS_SERVER(asList("windows server", "win server")),
    WINDOWS_7(asList("windows 7", "win 7")),
    WINDOWS_8(asList("windows 8", "win 8")),
    WINDOWS_10(asList("windows 10", "win 10")),
    WINDOWS_11(asList("windows 11", "win 11")),
    ARCH(asList("arch")),
    DEBIAN(asList("debian")),
    FEDORA(asList("fedora")),
    MINT(asList("mint")),
    UBUNTU(asList("ubuntu")),
    LIGAR(asList("ligar")),
    DESLIGAR(asList("desligar")),
    QUEIMAR(asList("queimar")),
    REINICIAR(asList("reiniciar")),
    ATUALIZAR(asList("atualizar")),
    TROCAR(asList("trocar")),
    SINCRONIZAR(asList("sincronizar")),
    CONECTAR(asList("conectar")),
    QUEBRAR(asList("quebrar")),
    ABRIR(asList("abrir")),
    FECHAR(asList("fechar")),
    EXECUTAR(asList("executar")),
    COMPARTILHAR(asList("compartilhar")),
    INTEGRAR(asList("integrar")),
    INSTALAR(asList("instalar")),
    DESINSTALAR(asList("desinstalar")),
    POSSO(asList("posso")),
    QUAL(asList("qual")),
    ONDE(asList("onde")),
    AONDE(asList("aonde")),
    QUANDO(asList("quando")),
    QUEM(asList("quem")),
    E_POSSIVEL(asList("é possível", "e possivel", "é possivel", "e possível")),
    QUANTO(asList("quanto")),
    COMPRAR(asList("comprar")),
    REEMBOLSAR(asList("reembolsar")),
    CORRIGIR(asList("corrigir")),
    CONSERTAR(asList("consertar")),
    CONSEGUIR(asList("conseguir")),
    CUSTAR(asList("custar")),
    MORAR(asList("morar"));

    private final List<String> descricao;

    EquipmentEnum(List<String> descricao) {
        this.descricao = descricao;
    }

}
